// <auto-generated />
using System;
using HMS.ContractsMicroService.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HMS.ContractsMicroService.Infrastructure.Migrations.WorkHours
{
    [DbContext(typeof(WorkHoursContext))]
    [Migration("20240918172629_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HMS.ContractsMicroService.Core.Entity.WorkHours", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EntryTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("ExitTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("IntervalEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("IntervalStartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("WorkHours");
                });
#pragma warning restore 612, 618
        }
    }
}
