// <auto-generated />
using System;
using HMS.PayrollMicroService.Infratructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HMS.PayrollMicroService.Infratructure.Migrations
{
    [DbContext(typeof(PayrollContext))]
    partial class PayrollContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HMS.PayrollMicroService.Core.Entity.Payroll", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HourlySalary")
                        .HasColumnType("int");

                    b.Property<short>("HoursWorkedInMonth")
                        .HasColumnType("smallint");

                    b.Property<int>("TotalAmountOfBenefits")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Payroll", (string)null);
                });

            modelBuilder.Entity("HMS.PayrollMicroService.Core.Entity.Payroll", b =>
                {
                    b.OwnsOne("HMS.PayrollMicroService.Core.Data.Discounts.Discount", "Discounts", b1 =>
                        {
                            b1.Property<Guid>("PayrollID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("MandatoryDiscounts")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("OtherDiscounts")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("TotalDiscounts")
                                .HasColumnType("int");

                            b1.HasKey("PayrollID");

                            b1.ToTable("Payroll");

                            b1.WithOwner()
                                .HasForeignKey("PayrollID");
                        });

                    b.Navigation("Discounts")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
