# Step 1: Buscar por arquivos .proto e listar
echo "Buscando arquivos .proto"
find HMS/HMS.MicroServices -type f -name "*.proto" > /tmp/protos/files.txt
if [ -s /tmp/protos/files.txt ]; then
  echo "Arquivos .proto encontrados:"
  cat /tmp/protos/files.txt
else
  echo "Nenhum arquivo .proto encontrado!"
  exit 1
fi

# Step 2: Criar diretório para armazenar arquivos
mkdir -p /tmp/protos

# Step 3: Criar diretórios necessários no repositório de destino
echo "Criando diretórios de destino no repositório grpc-proto-files"
while IFS= read -r file; do
  DIR_NAME=$(dirname "$file")
  echo "Criando diretório: /tmp/grpc-proto-files/ProtoFiles/$DIR_NAME"
  mkdir -p "/tmp/grpc-proto-files/ProtoFiles/$DIR_NAME"
done < /tmp/protos/files.txt

# Step 4: Copiar arquivos .proto para o repositório de destino
echo "Copiando arquivos .proto para o repositório grpc-proto-files"
while IFS= read -r file; do
  echo "Copiando $file para /tmp/grpc-proto-files/ProtoFiles/"
  cp "$file" /tmp/grpc-proto-files/ProtoFiles/"$(dirname "$file")/"
done < /tmp/protos/files.txt

# Step 5: Verificar arquivos copiados
echo "Verificando arquivos copiados"
ls -R /tmp/grpc-proto-files/ProtoFiles/

# Step 6: Commit e push para o repositório grpc-proto-files
echo "Fazendo commit e push dos arquivos copiados"
cd /tmp/grpc-proto-files
git status
git add .
git commit -m "Importando arquivos .proto de Projects-Release"
git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Jorge-Armando-Von-Doellinger/grpc-proto-files.git HEAD:main
