name: Copy Proto Files to grpc-proto-files Repo

on:
  push:
    paths:
      - '.github/workflows/copy-protos.yml'
      - 'HMS/HMS.MicroServices/**.proto'

jobs:
  copy-protos:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Listar diretórios principais
        run: ls -l

      - name: Listar diretório HMS
        run: ls -l HMS

      - name: Listar diretório HMS/HMS.MicroServices
        run: ls -l HMS/HMS.MicroServices || echo "Diretório não encontrado"

      - name: Encontrar e copiar arquivos .proto
        run: |
          if [ -d "HMS/HMS.MicroServices" ]; then
            echo "Encontrando arquivos .proto em HMS/HMS.MicroServices"
            mkdir -p /tmp/protos
            find HMS/HMS.MicroServices -type f -name "*.proto" -exec cp {} /tmp/protos/
          else
            echo "O diretório HMS/HMS.MicroServices não foi encontrado!"
            exit 1
          fi

      - name: Clonar repositório grpc-proto-files
        run: |
          git clone https://github.com/Jorge-Armando-Von-Doellinger/grpc-proto-files.git /tmp/grpc-proto-files

      # Step 6: Copiars arquivos .proto para o repositório grpc-proto-files
      - name: Copiar arquivos .proto para grpc-proto-files
        run: |
          if [ -d "/tmp/protos" ]; then
            cp /tmp/protos/* /tmp/grpc-proto-files/
            cd /tmp/grpc-proto-files
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add .
            git commit -m "Adicionando novos arquivos .proto"
            git push origin main
          else
            echo "Nenhum arquivo .proto foi encontrado para copiar!"
            exit 1
          fi

      # Step 7: Limpeza
      - name: Limpeza
        run: rm -rf /tmp/protos /tmp/grpc-proto-files
