name: Copy proto-files for the proto-repository

jobs: 
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Criar os diretorios destino
        run: mkdir -p /teste/proto

      - name: Encontrar todos os proto files
        run: |
          echo "Procurando arquivos"
          find . -type f -name "*.proto" -exec cp {} /teste/proto/ \;

      - name: Garantir permissoes
        run: chmod -R 755 /teste/proto/

      - name: Commit e push para grpc-proto-files
        run: |
          cd /teste/proto
          git add .
          git commit -m "Atualizando arquivos proto"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Jorge-Armando-Von-Doellinger/grpc-proto-files.git HEAD:main
