# Step 1: Exibir o diretório atual e procurar arquivos .proto
echo "Diretório atual: $(pwd)"
echo "Buscando arquivos .proto..."
find HMS/HMS.MicroServices -type f -name "*.proto" > /tmp/protos/files.txt

# Verifique se arquivos foram encontrados
if [ "$(find proto-files -type f)" ]; then
    echo "Arquivos encontrados, movendo..."
    find proto-files -type f -exec mv {} HMS/ProtoFiles/ \;
else
    echo "Nenhum arquivo encontrado para mover"
fi


# Step 2: Criar diretório para armazenar arquivos
echo "Criando diretório de destino para arquivos .proto"
mkdir -p /tmp/grpc-proto-files/ProtoFiles/HMS/HMS.MicroServices/

# Step 3: Copiar arquivos .proto encontrados para o diretório de destino
echo "Copiando arquivos .proto para /tmp/grpc-proto-files/ProtoFiles/"
while IFS= read -r file; do
  echo "Copiando $file para /tmp/grpc-proto-files/ProtoFiles/$(dirname "$file")"
  cp "$file" /tmp/grpc-proto-files/ProtoFiles/"$(dirname "$file")"/
done < /tmp/protos/files.txt

# Step 4: Verificar se os arquivos foram copiados
echo "Verificando arquivos copiados em /tmp/grpc-proto-files/ProtoFiles/"
ls -R /tmp/grpc-proto-files/ProtoFiles/

# Step 5: Commit e push para o repositório grpc-proto-files
cd /tmp/grpc-proto-files
git status
git add .
git commit -m "Importando arquivos .proto de Projects-Release"
git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Jorge-Armando-Von-Doellinger/grpc-proto-files.git HEAD:main
