name: Copy Proto Files to grpc-proto-files Repo

on:
  push:
    paths:
      - '.github/workflows/copy-protos.yml'
      - 'HMS/HMS.MicroServices/**/*.proto'

jobs:
  copy-protos:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Listar estrutura de diretórios para verificar onde estamos
      - name: Listar diretórios principais do repositório
        run: ls -l

      - name: Listar diretório 'HMS' e verificar se 'HMS.MicroServices' está presente
        run: |
          ls -l HMS
          ls -l HMS/HMS.MicroServices

      # Step 3: Encontrar arquivos .proto e verificar se existem
      - name: Encontrar arquivos .proto em HMS/HMS.MicroServices
        run: |
          echo "Procurando arquivos .proto em HMS/HMS.MicroServices/"
          find HMS/HMS.MicroServices -type f -name "*.proto" > /tmp/protos/files.txt
          if [ -s /tmp/protos/files.txt ]; then
            echo "Arquivos .proto encontrados:"
            cat /tmp/protos/files.txt
          else
            echo "Nenhum arquivo .proto encontrado em HMS/HMS.MicroServices/"
            exit 1
          fi

      # Step 4: Criar diretório de destino para os arquivos .proto
      - name: Criar diretório para arquivos .proto
        run: mkdir -p HMS/ProtoFiles/

      # Step 5: Copiar arquivos .proto para o diretório de destino
      - name: Copiar arquivos .proto para HMS/ProtoFiles
        run: |
          while IFS= read -r file; do
            echo "Copiando $file para HMS/ProtoFiles/"
            cp "$file" HMS/ProtoFiles/
          done < /tmp/protos/files.txt

      # Step 6: Verificar se os arquivos foram copiados corretamente
      - name: Verificar arquivos copiados para HMS/ProtoFiles
        run: ls -l HMS/ProtoFiles/

      # Step 7: Clonar repositório grpc-proto-files
      - name: Clonar repositório grpc-proto-files
        run: |
          git clone https://github.com/Jorge-Armando-Von-Doellinger/grpc-proto-files.git /tmp/grpc-proto-files

      # Step 8: Copiar os arquivos .proto para o repositório grpc-proto-files
      - name: Copiar arquivos .proto para grpc-proto-files
        run: |
          if [ "$(ls -A HMS/ProtoFiles)" ]; then
            echo "Arquivos encontrados em HMS/ProtoFiles. Copiando para grpc-proto-files..."
            cp HMS/ProtoFiles/* /tmp/grpc-proto-files/
            cd /tmp/grpc-proto-files
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git status
            git add .
            git commit -m "Adicionando novos arquivos .proto"
            git push origin main
          else
            echo "Não há arquivos .proto para copiar!"
            exit 1
          fi

      # Step 9: Limpeza
      - name: Limpeza
        run: rm -rf /tmp/protos /tmp/grpc-proto-files
