name: Copiar arquivos proto para outro repositório

on: push

jobs:
  copiar-arquivos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório de origem
        uses: actions/checkout@v3

      - name: Criar diretório para arquivos proto
        run: mkdir -p /tmp/proto

      - name: Encontrar e copiar arquivos proto
        run: |
          find . -type f -name "*.proto" -exec cp {} /tmp/proto/ \;

      - name: Checkout repositório de destino
        uses: actions/checkout@v3
        with:
          repository: Jorge-Armando-Von-Doellinger/grpc-proto-files
          token: ${{ secrets.GITHUB_TOKEN }}
          path: grpc-proto-files

      - name: Copiar arquivos para o repositório de destino
        run: cp -r /tmp/proto/* rpc-proto-files/

      - name: Commit e push para o repositório de destino
        run: |
          cd grpc-proto-files
          git config --global user.email "jorgearmandovdj@gmail.com"
          git add user.name "Jorge"
          git add .
          git commit -m "Adicionando arquivos proto"
          git push origin main
